name: WordPress CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Save config wordpress
        run: echo "APACHE_WPHOST_CONFIG=
                      <VirtualHost *:3000>
                        DocumentRoot /home/runner/work/FastService/FastService/
                        <Directory /home/runner/work/FastService/FastService/>
                            Options FollowSymLinks
                            AllowOverride Limit Options FileInfo
                            DirectoryIndex index.php
                            Require all granted
                        </Directory>
                        <Directory /home/runner/work/FastService/FastService/wp-content>
                            Options FollowSymLinks
                            Require all granted
                        </Directory>
                      </VirtualHost>
                  " >> $GITHUB_ENV

      - name: Save config default
        run: echo "APACHE_DEFAULT_CONFIG=
                      <VirtualHost *:80>
                        ServerAdmin webmaster@localhost
                        DocumentRoot /var/www/html
                        ProxyPreserveHost On
                        ProxyPass / localhost:3000/
                        ProxyPassReverse / localhost:3000/
                        RequestHeader set X-FORWARDED-PROTO 'https'
                        ErrorLog ${APACHE_LOG_DIR}/error.log
                        CustomLog ${APACHE_LOG_DIR}/access.log combined
                      </VirtualHost>
                  " >> $GITHUB_ENV

      - name: MySQL for Wordpress
        run: |
          sudo systemctl start mysql
          mysql -h localhost -u root -proot -e "
            create table wordpress;
            CREATE USER wordpress@localhost IDENTIFIED BY '<your-password>';
            GRANT SELECT,INSERT,UPDATE,DELETE,CREATE,DROP,ALTER ON wordpress.* TO wordpress@localhost;
            FLUSH PRIVILEGES;
            quit
            "

      - name: Execute SQL commands
        run: |
          sudo systemctl start mysql
          mysql -h localhost -u root -p"${MYSQL_ROOT_PASSWORD}" -e "show databases"

      - name: Server Configuration
        run: |
          sudo touch /etc/apache2/sites-available/wordpress.conf
          echo "$APACHE_WPHOST_CONFIG" > sudo tee /etc/apache2/sites-available/wordpress.conf
          echo "$APACHE_DEFAULT_CONFIG" >> sudo tee /etc/apache2/sites-available/000-default.conf
          sudo a2ensite wordpress
          sudo a2enmod rewrite
          sudo a2enmod proxy
          sudo a2enmod proxy_http
          sudo a2enmod headers
          sudo systemctl restart apache2
        
      - name: Env setup
        run: |
          sudo apt install ghostscript \
                libapache2-mod-php \
                mysql-server \
                php \
                php-bcmath \
                php-curl \
                php-imagick \
                php-intl \
                php-json \
                php-mbstring \
                php-mysql \
                php-xml \
                php-zip

      - name: Open port 3000 for wordpress
        run: |
          echo "Listen 3000" | sudo tee -a /etc/apache2/ports.conf
          sudo systemctl reload apache2
          sudo lsof -i -P -n | grep LISTEN
          curl localhost:3000
          ls -l /home/runner/work/FastService/FastService/
