name: WordPress CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Env setup
        run: |
          sudo apt install apache2 \
                 ghostscript \
                 libapache2-mod-php \
                 mysql-server \
                 php \
                 php-bcmath \
                 php-curl \
                 php-imagick \
                 php-intl \
                 php-json \
                 php-mbstring \
                 php-mysql \
                 php-xml \
                 php-zip

      - name: Something
        run: |
          sudo systemctl start apache2
          curl localhost:80

      - name: Deploy WordPress
        # You may pin to the exact commit or the version.
        # uses: rtCamp/action-deploy-wordpress@2f2e1345ac53cee3eeef97691d196a41cfed0780
        uses: rtCamp/action-deploy-wordpress@v3.1.0
