name: WordPress CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Save config
        run: echo "APACHE_WPHOST_CONFIG=
                      <VirtualHost *:3000>
                        DocumentRoot /srv/www/wordpress
                        <Directory /srv/www/wordpress>
                            Options FollowSymLinks
                            AllowOverride Limit Options FileInfo
                            DirectoryIndex index.php
                            Require all granted
                        </Directory>
                        <Directory /srv/www/wordpress/wp-content>
                            Options FollowSymLinks
                            Require all granted
                        </Directory>
                      </VirtualHost>
                  " >> $GITHUB_ENV

      # - name: Setup reverse proxy
      #   run: echo "APACHE_DEFAULT_CONFIG=
      #     <VirtualHost *:80>                 
      #       ServerAdmin webmaster@localhost
      #       DocumentRoot /var/www/html
      #       ProxyPreserveHost On
      #       ProxyPass / localhost:3000/
      #       ProxyPassReverse / localhost:3000/
      #       RequestHeader set X-FORWARDED-PROTO 'https'
      #       ErrorLog ${APACHE_LOG_DIR}/error.log
      #       CustomLog ${APACHE_LOG_DIR}/access.log combined
      #     </VirtualHost>
      #     " >> $GITHUB_ENV

      - name: Save environment variable to a file
        run: |
          sudo touch /etc/apache2/sites-available/wordpress.conf
          echo "$APACHE_WPHOST_CONFIG" > sudo tee /etc/apache2/sites-available/wordpress.conf
          echo "$APACHE_DEFAULT_CONFIG" >> sudo tee /etc/apache2/sites-available/000-default.conf
          sudo a2ensite wordpress
          sudo a2enmod rewrite
          ls /etc/apache2/sites-enabled/

      - name: Display the content of nginx.conf
        run: cat /etc/apache2/sites-available/wordpress.conf
        
      # - name: Env setup
      #   run: |
      #     sudo apt install apache2 \
      #            ghostscript \
      #            libapache2-mod-php \
      #            mysql-server \
      #            php \
      #            php-bcmath \
      #            php-curl \
      #            php-imagick \
      #            php-intl \
      #            php-json \
      #            php-mbstring \
      #            php-mysql \
      #            php-xml \
      #            php-zip

      - name: Open port 3000 for wordpress
        run: |
          sudo systemctl start apache2
          sudo sed -i '/^LISTEN 80/a LISTEN 3000' /etc/apache2/ports.conf
          sudo systemctl reload apache2
